### ISSUE TITLE
Support different app versions

### ISSUE THREAD

**Issue by Fardenco** [witnessmenow/arduino-facebook-api#3]
I could be great to be able to set the app version we're using in the constructor.
I did generate a permanent access token a while ago under v2.8, and didn't want to create another app so I had to change the lib code to replace "/v2.9/" by "/v2.8/" because the request is rejected if the app version is not the right one.
It could be done with an optional parameter on the constructor, with a default value of "2.9"

**Comment by witnessmenow** [comment]
Sounds like a good suggestion! Would you have any interest in raising a PR
for this? It would he great if it could be made optional (where it defaults
to whatever is there)

On another note, do you have a link to the instructions you used for the
perm token?

Thanks,
Brian

**Comment by Fardenco** [comment]
I did use the same instructions as the ones you told about on the other thread
https://stackoverflow.com/questions/17197970/facebook-permanent-page-access-token

I'll do a pull request, but I'd like to hear what you think
Do you think it's more convenient to ask only for the version number (like "2.9") or to ask the full version name (like "v2.9") ?

**Comment by witnessmenow** [comment]
Maybe keep it "v2.9" for extra flexibility

Thanks!

**Comment by Fardenco** [comment]
I did the changes, they are really minors but nonetheless I'd like to test everything before pulling. Right now I don't have access to an esp8266, I ordered a few ones, and I'll update as soon as I'll have been able to ensure that everything works fine.

**Comment by Fardenco** [comment]
It seems like the Facebook API has changed, the request is now working even with the wrong version number
My app is v2.8, but it works if I let v2.9 in the url.
No more issue I guess =)
